pypxe/dhcp.py, pypxe/tftp.py
Previously we would crash when we ran out of leases. This fix uses a custom exception which we ride up to `listen` and then log to critical.
This also fixes a TFTP "file not found" error and an error message regression.
=> Fix DHCP running out of leases, Fix TFTP "file not found" and associated error regression

README.md, pypxe-server.py
Adjust documentation and `--help` to reflect support for negating debug modes via CLI options
=> Adjust Documentation to Reflect CLI Debug Negation

pypxe-server.py, pypxe/nbd/writes.py
Fixes the following:
* Argument variable name change was not global
* `get_child` in nbd writes.py was wrong
With the initial debug logging block, there are a lot of lines that duplicate the service name in the log format string and the actual log message. For example:
```
2015-05-12 17:30:51,190 [DEBUG] PyPXE.TFTP TFTP Server IP: 0.0.0.0
2015-05-12 17:30:51,190 [DEBUG] PyPXE.TFTP TFTP Server Port: 69
2015-05-12 17:30:51,190 [DEBUG] PyPXE.TFTP TFTP Network Boot Directory: .
```
Should we remove the second `TFTP`, as it is already present in the logging namespace?
=> Minor Bug Fixes for v1.6

pypxe/tftp.py
I realized last night that duplicate acks for block 0 would incorrectly increase the wrap count. This makes it only increment the wrap after having gone half way through the sequence space. I've tested this against the tftp client in Tiny Core, FreeBSD, iPXE, and pxelinux without problems.
This is a much smaller bug than psychomario/PyPXE#95 since it would only occur on duplicate acks of block 0.
=> Only Increment Wrap after Going Half-way Through

pypxe/tftp.py
Always seek to the block we want to read.
I don't think there is any unneccessary overhead as `.seek()` doesn't actually read the file, just moves the `.read()` pointer.
Fixes #98
=> Always Seek to Correct Block

.gitignore, DOCUMENTATION.md, README.md, pypxe/server.py, setup.py
Moved `pypxe-server.py` to be `pypxe.server`, and made modifications required for that to work. Added a `setuptools` install script. Added relevant `.gitignore` bits for that.
[root@icb:~] # cd PyPXE-icb
[root@icb:~/PyPXE-icb] # python setup.py install
running install
running bdist_egg
running egg_info
writing PyPXE.egg-info/PKG-INFO
writing top-level names to PyPXE.egg-info/top_level.txt
writing dependency_links to PyPXE.egg-info/dependency_links.txt
writing entry points to PyPXE.egg-info/entry_points.txt
reading manifest file 'PyPXE.egg-info/SOURCES.txt'
writing manifest file 'PyPXE.egg-info/SOURCES.txt'
installing library code to build/bdist.freebsd-10.1-RELEASE-amd64/egg
running install_lib
running build_py
creating build/bdist.freebsd-10.1-RELEASE-amd64/egg
creating …
=> Added setuptools script. Refactored CLI entry point.

pypxe/helpers.py, pypxe/http.py, pypxe/server.py, pypxe/tftp.py
Removed the `os.chroot()` path traversal protection hack, and replaced it with detecting path traversal outside the `netboot_directory` given.
I've verified that access to files in `HTTPD` and `TFTPD` both work, and that I've been unable to escape `netboot_directory`. I don't have a setup where I'm able to test `NBD`, but from looking at the code, I'm not sure how it could've worked in the past without having the `block_device` be inside and relative to `netboot_directory`.
=> Removed os.chroot() and replaced with proper path traversal detection

pypxe/tftp.py
Write opcode error sending was missing from TFTP.
If opcode == write, open socket, send error and mark socket as dead.
=> Added TFTP 'put' Error

pypxe/dhcp.py, pypxe/http.py, pypxe/nbd/nbd.py, pypxe/server.py, pypxe/tftp.py
* Fixed scope issue in `server.py`, causing a crash when nbd is used
* Cast port numbers to `int`, fixing CLI port options
* Normalize NBD block device path for when we're opening.
* Make `--nbd-cow` imply `--nbd-write`, as otherwise `--nbd-cow` does nothing and the client is still readonly.
Aplogies for multiple fixes in one PR, but they are all one liners or so, so I didn't think they warranted their own PRs, but they have their own commits.
=> Multiple Bug Fixes

pypxe/dhcp.py
Fixes the following crash:
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "pypxe/dhcp.py", line 355, in listen
self.dhcp_offer(message)
File "pypxe/dhcp.py", line 293, in dhcp_offer
options_response = self.craft_options(2, client_mac) # DHCPOFFER
File "pypxe/dhcp.py", line 269, in craft_options
if 93 in self.leases[client_mac]['options'] and not self.force_file_name:
KeyError: 'options'
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> pypxe/dhcp.py: avoid exception when leases have no options

pypxe/tftp.py
Some clients will reject an OACK which has blksize and tsize if the
request had only blksize. This commit fixes this issue.
RFC2347 states that 'The server must not include in the OACK any option
which had not been specifically requested by the client'.
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> tftp.py: do not include tsize in OACK if it was not in the request

pypxe/tftp.py
The TFTP server needlessly loops on the select call due to the zero
timeout value. Set timeout to 1s to conserve CPU while still allowing
re-transmission in case an ACK is lost.
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> pypxe/tftp.py: set select timeout to 1 to reduce CPU usage

pypxe/helpers.py, pypxe/nbd/writes.py, pypxe/server.py, pypxe/tftp.py
Implement Logger.getChild ourselves since that doesn't exist in Python 2.6.
Resolves psychomario/PyPXE#136
=> Implement Logger.getChild ourselves

README.md, example_cfg.json, pypxe/server.py, setup.py
@Apachez- asked to have the TFTP server bind address exposed in psychomario/PyPXE#151. This does that as `--tftp-server-ip` on the command line, and `TFTP_SERVER_IP` in the config, following the same conventions as similar options for the DHCP server.
=> Expose TFTP bind IP address

pypxe/dhcp.py, pypxe/server.py, setup.py
#147 broken apart with just the simple Python3 changes.
1. setup.py will display the error now vs just failing
2. exception splitting in dhcp.py works across Python versions
3. file open changes, using io.open works across Python versions
4. Print is a function, no future import needed. https://docs.python.org/2.6/library/functions.html#print
Disclaimer, I did the proof of concept for Ansible and Python3, not my first roller coaster.
will note the getuid vs geteuid in another PR
=> Python3 lowpass changes, zero impact to Python 2.6+

README.md
The documented option doesn't exist. Update documentation to match reality
=> Update documentation to match reality

pypxe/tftp.py
As documented in RFC 2347 page 3, the server MUST NOT ack an option not requested first by the client.
This change makes possible to PXE a Raspberry PI 3B+.
=> Do not ack an option if the client didn't request it first

pypxe/server.py
Python3 did away with the 'unicode' tag renaming in 'str'. This causes PyPXE in python 3 to bail out if we load a JSON config.
Ref: https://stackoverflow.com/questions/19877306/nameerror-global-name-unicode-is-not-defined-in-python-3
Error: Traceback (most recent call last):
File "/usr/local/bin/pypxe", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/site-packages/pypxe/server.py", line 164, in main
if type(loaded_config[setting]) is unicode:
NameError: name 'unicode' is not defined
=> Update server.py for Python3

pypxe/server.py
My sincere apologies. My previous "fix" missed the point of the the conversion in the first place. we expect all JSON values to be Strings or Bools so we encode bytes into string. This blunder would only have been apparent if someone loaded a JSON config.
=> Fix an embarrassing mistake

pypxe/nbd/writes.py, pypxe/server.py
There are small typos in:
- pypxe/nbd/writes.py
- pypxe/server.py
Fixes:
- Should read `definite` rather than `definate`.
- Should read `passed` rather than `pased`.
- Should read `definitely` rather than `definately`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

pypxe/dhcp.py
Fixes the following crash:
Traceback (most recent call last):
[...]
File "/usr/lib/python3.10/site-packages/pypxe/dhcp.py", line 145, in export_leases
json.dump(export_safe, leases_file)
File "/usr/lib/python3.10/json/__init__.py", line 180, in dump
fp.write(chunk)
TypeError: a bytes-like object is required, not str
=> pypxe/dhcp.py: avoid exception when invoking export_leases

pypxe/dhcp.py, pypxe/server.py
"Silently" installing signal handlers from a module that may be
imported from another project is not the best idea.
Instead we move them to the server, which is where we want them here
and as an usage example for other PyPXE users.
=> dhcp: only install signal handlers from the server
